version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:0-1.20
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  db:
    image: mongo:4.4.1
    container_name: mongo